####################
# User Service API # 
####################

### Test for API Gateway
GET http://localhost:3000/
Content-Type: application/json

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name": "Rebison",
    "email": "rebison85@gmail.com",
    "password": "123456"
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "rebison85@gmail.com",
  "password": "123456"
}


###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Zjc0ZmQzYWJlMDEwY2VkOTdjNmEzOSIsImlhdCI6MTc2MTExNTg3NCwiZXhwIjoxNzYzNzA3ODc0fQ.QuFY4wJ-pkXbasaXycF1L2EQBL6plQO_xDy0F1UkJ3k
GET http://localhost:3000/api/users/profile
Authorization: Bearer {{token}}
Content-Type: application/json

#####################
# Order Service API #
#####################

###
POST http://localhost:3000/api/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": "68f74fd3abe010ced97c6a39",
    "productId": "68f75794a38bd933fceb4604",
    "quantity": 2
}