POST http://localhost:3003
Content-Type: application/json

{
    "userId": "68f74fd3abe010ced97c6a39",
    "productId": "68f75794a38bd933fceb4604",
    "quantity": 2
}

###
GET http://localhost:3003
Content-Type: application/json